Dæmi 1-útsýring
Upplysingaverkfraedi/postgresql-baratheon pull request #3
Opened 2024-10-10 22:24 UTC by snaeja13

Útskyring fyrir kóða á dæmi 1, liður 1-3

2024-10-10 22:36 UTC, erlendur235 commented
Ég finn ekki útskýringar skjalið, ertu viss að þú sért búinn að commita það?

2024-10-10 22:37 UTC, erlendur235 commented
Eða það kemur bara load DIFF, geturu prófað að gera markdown skjal og commita því?

2024-10-10 22:42 UTC, erlendur235 commented
Sorry, þetta er hérna inni, sýnist þær vera góðar

2024-10-10 22:47 UTC, erlendur235 commented
Mátt kannski breyta útskýringarskjalinu í md skjal svo það sé þæginlegra að breyta í pdf

2024-10-10 22:51 UTC, dalrosInga requested changes
Skoðaði lið 2 en næ ekki heldur ekki að laga hann þannig að það komi ekki villa svo mín vegna verðum við bara að skila honum svona, hinir liðirnir flottir!
Held að það sé betra að vinna með útskýringarnar í markdown skjali, gætiru breytt þeim?

2024-10-10 22:57 UTC, snaeja13 commented
Breytti yfir í markdown skjal

2024-10-10 23:12 UTC, erlendur235 approved these changes
Skilar tölfunni rétt en skilar ekki alveg því sem á að skila í lið 2, ég er búinn að vera að reyna að laga þetta en ég næ ekki að skila því sem á að skila. Hinir liðirnir eru góðir

2024-10-10 23:14 UTC, dalrosInga approved these changes
flott

2024-10-10 23:14 UTC, merged

2024-10-30 19:13 UTC, tungufoss commented
@erlendur235 @dalrosInga : keyrðu þið þennan kóða sjálf? Hann nefnilega virkar ekki hjá mér... það er verið að vísa í töfluheiti sem er ekki til og það er duplicate error. Aftur á móti er réttur SQL kóði að finna í skýrslunni, en það er ósamræmi á þeim SQL fyrirspurnum og þeim sem er í SQL skjalinu

Það dugar ekki bara að fara einungis efnislega yfir kóðann frá @snaeja13, heldur þurfið þið líka að prófa að keyra hann sjálf hjá ykkur.